### ISSUE TITLE
How can we use this with Recorded audio

### ISSUE THREAD

**Issue by gouravd** [Yalantis/Horizon#1]
I tried my luck with Visualizer and sending the byte[] data from Visualizer.setDataCaptureListener but the vizualization is not syncronized.

I tried both Waveformdata and FFTData

**Comment by Cool04ek** [comment]
Hi. You don't need Visualiser in this case. You can just send raw data from InputStream. 
Something like:

InputStream is = new FileInputStream("some_audio.wav");
byte[] buffer = new byte[bufferSize];
is.read(buffer);
mHorizon.updateView(buffer);

Take a note, that you need WAV audio in order to get proper analysis.
